### ISSUE TITLE
Search result class has same name as useful object: “Languoid”

### ISSUE THREAD

**Issue by Anaphory** [clld/pyglottolog#9]
I just ran into some confusion because the name of the result type of a search https://github.com/clld/pyglottolog/blob/6d0be4d9e568c89c0db327b9bbb51ed7f414cc5c/src/pyglottolog/fts.py#L18-L24 coincides with the name of the useful class that allows me to eg. climb the Glottolog tree and find location data
https://github.com/clld/pyglottolog/blob/6d0be4d9e568c89c0db327b9bbb51ed7f414cc5c/src/pyglottolog/languoids/languoid.py#L26-L30
Is this intentional? Why does the search not return the latter type, would that break anything?

**Comment by xrotwang** [comment]
The two classes have the same name, because they are both representations of what's called a "languoid" in Glottolog. Ideally, the full-text-search would return full-fledged `pyglottolog.languoids.languoid.Languoid` instances - but for this to work, there would need to be a lot more marshalling/un-marshalling of data when writing the index and reading from the index.
